name: Test PyPI Connection

on:
  workflow_dispatch: 

permissions:
  id-token: write  

jobs:
  test-connection:
    name: Test PyPI Connection
    runs-on: ubuntu-latest
    environment: DEPLOY_TO_TEST_PYPI 
    
    steps:
    - name: Install twine
      run: |
        pip install twine
    
    - name: Verify PyPI configuration
      run: |
        echo "Testing connection to PyPI..."
        python -m twine check --strict README.md || true
        
    - name: Test OIDC token retrieval
      uses: actions/github-script@v7
      with:
        script: |
          const token = await core.getIDToken();
          console.log('Successfully retrieved OIDC token');
          console.log('Token length:', token.length);
          
    - name: Test PyPI API
      run: |
        curl -sSI https://test.pypi.org/pypi | grep "HTTP"
        echo "Connection to TestPyPI successful"
        
        curl -sSI https://pypi.org/pypi | grep "HTTP"
        echo "Connection to PyPI successful" 